// Definição das perguntas de Controle de Qualidade para TOMBADORES
// Estrutura: setor -> perguntas com código, descrição, requer imagem, opções

export interface CQPergunta {
  codigo: string;
  descricao: string;
  etapa: string;
  avaliacao: string;
  medidaCritica: string;
  metodoVerificacao: string;
  instrumento: string;
  criteriosAceitacao: string;
  opcoes: ('Conforme' | 'Não conforme' | 'Não Aplicável')[];
  requerImagem: boolean;
  imagemDescricao?: string;
}

export interface CQSetor {
  codigo: string;
  nome: string;
  processo: string;
  perguntas: CQPergunta[];
}

// ============================================================================
// CQ-A: CORTE
// ============================================================================
export const CQ_A_CORTE: CQSetor = {
  codigo: 'A',
  nome: 'CORTE',
  processo: 'A - CORTE',
  perguntas: [
    {
      codigo: 'CQ1-A',
      descricao: 'MEDIDA TOTAL DE CORTE DA VIGA',
      etapa: 'VIGA',
      avaliacao: '100%',
      medidaCritica: 'Comprimento total (após esquadro pronto)',
      metodoVerificacao: 'Dimensional',
      instrumento: 'Trena',
      criteriosAceitacao: '+/- 10 mm',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ2-A',
      descricao: 'VERIFICAR DETALHE PARA CORTE DE ENCAIXE DE VIGA',
      etapa: 'VIGA',
      avaliacao: '100%',
      medidaCritica: 'Medida de corte da aba e presença de chanfro',
      metodoVerificacao: 'Dimensional',
      instrumento: 'Trena',
      criteriosAceitacao: '+/- 5 mm',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ3-A',
      descricao: 'VERIFICAR DISTRIBUIÇÃO DAS VIGAS E MEDIDA TOTAL (IDENTIFICAÇÃO DA VIGA 72/82/92)',
      etapa: 'VIGA',
      avaliacao: '100%',
      medidaCritica: 'Comprimento e identificação das vigas',
      metodoVerificacao: 'Dimensional; Visual',
      instrumento: 'Trena',
      criteriosAceitacao: '+/- 8 mm. Seguir conforme desenho.',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA IDENTIFICAÇÃO DAS VIGAS',
    },
  ],
};

// ============================================================================
// CQ-B: MONTAGEM SUPERIOR E ESQUADRO
// ============================================================================
export const CQ_B_MONTAGEM: CQSetor = {
  codigo: 'B',
  nome: 'MONTAGEM SUPERIOR E ESQUADRO',
  processo: 'B - MONTAGEM SUPERIOR E ESQUADRO',
  perguntas: [
    {
      codigo: 'CQ1-B',
      descricao: 'MEDIDA DA MONTAGEM INICIAL (CONFORME DESENHO ETAPA 0)',
      etapa: 'VIGA',
      avaliacao: '100%',
      medidaCritica: 'Comprimento; Largura',
      metodoVerificacao: 'Dimensional',
      instrumento: 'Trena',
      criteriosAceitacao: '+/- 5 mm',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA IDENTIFICAÇÃO DAS VIGAS',
    },
    {
      codigo: 'CQ2-B',
      descricao: 'ESQUADRO',
      etapa: 'VIGA',
      avaliacao: '100%',
      medidaCritica: 'Comprimento; Ângulo',
      metodoVerificacao: 'Dimensional',
      instrumento: 'Trena; Esquadro',
      criteriosAceitacao: '+/- 5 mm; +/- 1 grau',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ3-B',
      descricao: 'POSICIONAMENTO DO TRAVA CHASSI COD.24569 (CONFORME DESENHO ETAPA 0)',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Comprimento',
      metodoVerificacao: 'Dimensional',
      instrumento: 'Trena',
      criteriosAceitacao: '+/- 5 mm',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ4-B',
      descricao: 'POSICIONAMENTO DO APOIO DO TRAVADOR DE RODAS COD. 23691 (CONFORME DESENHO ETAPA 1)',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Comprimento',
      metodoVerificacao: 'Dimensional',
      instrumento: 'Trena',
      criteriosAceitacao: '+/- 5 mm',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ5-B',
      descricao: 'POSICIONAMENTO DO APOIO DO TRAVADOR DE RODAS COD. 23789 (CONFORME DESENHO ETAPA 1)',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Comprimento',
      metodoVerificacao: 'Dimensional',
      instrumento: 'Trena',
      criteriosAceitacao: '+/- 5 mm',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ6-B',
      descricao: 'MONTAGEM DA MÃO FRANCESA E PRESENÇA DE OLHAL (COD. 23709 NO APOIO TRAVA RODAS)',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'N/A',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Conforme desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA MONTAGEM DA MÃO FRANCESA',
    },
    {
      codigo: 'CQ7-B',
      descricao: 'SOLDA DA MÃO FRANCESA DE APOIO DO TRAVA RODAS',
      etapa: 'SOLDA',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA SOLDA DA MÃO FRANCESA',
    },
    {
      codigo: 'CQ8-B',
      descricao: 'POSICIONAMENTO E ESPAÇAMENTO DOS GRAMPOS COD. 23694 (CONFORME DESENHO ETAPA 1)',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Espaçamento entre grampos; Quantidade de grampos',
      metodoVerificacao: 'Dimensional; Visual',
      instrumento: 'Trena',
      criteriosAceitacao: '+/- 2 mm; Conforme desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DO POSICIONAMENTO DOS GRAMPOS',
    },
    {
      codigo: 'CQ9-B',
      descricao: 'FECHAMENTO FRONTAL GRADEADO COD. 24845',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'N/A',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Conforme desenho',
      opcoes: ['Conforme', 'Não conforme', 'Não Aplicável'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DO FECHAMENTO FRONTAL GRADEADO',
    },
    {
      codigo: 'CQ10-B',
      descricao: 'MONTAGEM DA BARRA CHATA NO LAVRADO COD. 23103',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'N/A',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Conforme desenho',
      opcoes: ['Conforme', 'Não conforme', 'Não Aplicável'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA MONTAGEM DA BARRA CHATA',
    },
    {
      codigo: 'CQ11-B',
      descricao: 'POSICIONAMENTO E ESPAÇAMENTO DOS GRAMPOS PARA BARRA REDONDA COD 25623 (CONFORME DESENHO ETAPA 1)',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Espaçamento entre grampos; Quantidade de grampos',
      metodoVerificacao: 'Dimensional; Visual',
      instrumento: 'Trena',
      criteriosAceitacao: '+/- 5 mm; Conforme desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DO POSICIONAMENTO E ESPAÇAMENTO DOS GRAMPOS',
    },
    {
      codigo: 'CQ12-B',
      descricao: 'CONFERIR BARRAS REDONDAS SE ESTÃO POSICIONADAS CORRETAMENTE',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Espaçamento entre grampos; Quantidade de grampos',
      metodoVerificacao: 'Dimensional; Visual',
      instrumento: 'Trena',
      criteriosAceitacao: '+/- 5 mm; Conforme desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DAS BARRAS REDONDAS POSICIONADAS',
    },
    {
      codigo: 'CQ13-B',
      descricao: 'MONTAGEM DO REFORÇO TRANSVERSAL PARA ASSOALHO (CONFORME MEDIDAS DESENHO ETAPA 1)',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'N/A',
      metodoVerificacao: 'Dimensional; Visual',
      instrumento: 'Trena',
      criteriosAceitacao: '+/- 5 mm; Conforme desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA MONTAGEM DO REFORÇO TRANSVERSAL',
    },
    {
      codigo: 'CQ14-B',
      descricao: 'MONTAGEM DE PERFIL 50X70 CONFORME DESENHO ASSINADO',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'N/A',
      metodoVerificacao: 'Dimensional; Visual',
      instrumento: 'Trena',
      criteriosAceitacao: '+/- 5 mm; Conforme desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA MONTAGEM DE PERFIL 50X70',
    },
    {
      codigo: 'CQ15-B',
      descricao: 'MONTAGEM DE REFORÇOS SUPERIORES (CONFORME DESENHO)',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'N/A',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Conforme desenho',
      opcoes: ['Conforme', 'Não conforme', 'Não Aplicável'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA MONTAGEM DE REFORÇOS SUPERIORES',
    },
    {
      codigo: 'CQ16-B',
      descricao: 'SOLDA DE REFORÇOS SUPERIORES',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA SOLDA DE REFORÇOS SUPERIORES',
    },
    {
      codigo: 'CQ17-B',
      descricao: 'SOLDA DO REFORÇO DO PISO COM PERFIL 50X70 PARTE SUPERIOR',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA SOLDA DO REFORÇO DO PISO',
    },
    {
      codigo: 'CQ18-B',
      descricao: 'MONTAGEM TAMPA TRAVA RODAS CHAPA PISO COD. 23698',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'N/A',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Conforme desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA MONTAGEM TAMPA TRAVA RODAS',
    },
    {
      codigo: 'CQ19-B',
      descricao: 'SOLDA TAMPA TRAVA RODAS',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA SOLDA TAMPA TRAVA RODAS',
    },
    {
      codigo: 'CQ20-B',
      descricao: 'SOLDA EMENDAS DAS VIGAS INFERIORES',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme', 'Não Aplicável'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA SOLDA EMENDAS DAS VIGAS INFERIORES',
    },
    {
      codigo: 'CQ21-B',
      descricao: 'SOLDA EMENDA DAS VIGAS SUPERIORES',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA SOLDA EMENDA DAS VIGAS SUPERIORES',
    },
    {
      codigo: 'CQ22-B',
      descricao: 'OLHAL DE IÇAMENTO CONFORME DESENHO COD. 23694',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'N/A',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Conforme Desenho',
      opcoes: ['Conforme', 'Não conforme', 'Não Aplicável'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DO OLHAL DE IÇAMENTO',
    },
    {
      codigo: 'CQ23-B',
      descricao: 'MONTAGEM CHAPA DE DESCIDA RÁPIDA',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'N/A',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Conforme desenho',
      opcoes: ['Conforme', 'Não conforme', 'Não Aplicável'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA MONTAGEM CHAPA DE DESCIDA RÁPIDA',
    },
    {
      codigo: 'CQ24-B',
      descricao: 'SOLDA CHAPA DE DESCIDA RÁPIDA',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme', 'Não Aplicável'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA SOLDA CHAPA DE DESCIDA RÁPIDA',
    },
    {
      codigo: 'CQ25-B',
      descricao: 'SOLDA OLHAL DE IÇAMENTO (SOLDA A SUBIR)',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA SOLDA OLHAL DE IÇAMENTO',
    },
    {
      codigo: 'CQ26-B',
      descricao: 'VERIFICAR SE ARTICULADOR DE 2" ESTÁ MONTADO COD. 12570',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'N/A',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Conforme Desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DO ARTICULADOR',
    },
    {
      codigo: 'CQ27-B',
      descricao: 'MONTAGEM CHAPA 1050X3000 COD. 23806',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'N/A',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Conforme desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA MONTAGEM CHAPA 1050X3000',
    },
    {
      codigo: 'CQ28-B',
      descricao: 'SOLDA CHAPA 1050X2980',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA SOLDA CHAPA 1050X2980',
    },
    {
      codigo: 'CQ29-B',
      descricao: 'MONTAGEM SUPORTE CALHAS (ETAPA 5, COD. 27948, 27949 E 27958)',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'N/A',
      metodoVerificacao: 'Visual',
      instrumento: 'Gabarito',
      criteriosAceitacao: 'Conforme desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA MONTAGEM SUPORTE CALHAS',
    },
    {
      codigo: 'CQ30-B',
      descricao: 'SOLDA SUPORTE CALHAS',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA SOLDA SUPORTE CALHAS',
    },
    {
      codigo: 'CQ31-B',
      descricao: 'MONTAGEM TAMPA DE PROTEÇÃO TRAVA CHASSI',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'N/A',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Conforme desenho',
      opcoes: ['Conforme', 'Não conforme', 'Não Aplicável'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA MONTAGEM TAMPA DE PROTEÇÃO',
    },
    {
      codigo: 'CQ32-B',
      descricao: 'SOLDA TAMPA DE PROTEÇÃO TRAVA CHASSI',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA SOLDA TAMPA DE PROTEÇÃO',
    },
    {
      codigo: 'CQ33-B',
      descricao: 'SUPORTE PARA TRAVA PINOS',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'N/A',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Conforme desenho',
      opcoes: ['Conforme', 'Não conforme', 'Não Aplicável'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DO SUPORTE PARA TRAVA PINOS',
    },
    {
      codigo: 'CQ34-B',
      descricao: 'SOLDA SUPORTE TRAVA PINO',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA SOLDA SUPORTE TRAVA PINO',
    },
    {
      codigo: 'CQ35-B',
      descricao: 'MONTAGEM SUPORTE CALÇO MECÂNICO',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'N/A',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Conforme desenho',
      opcoes: ['Conforme', 'Não conforme', 'Não Aplicável'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA MONTAGEM SUPORTE CALÇO MECÂNICO',
    },
    {
      codigo: 'CQ36-B',
      descricao: 'SOLDA SUPORTES CALÇO MECÂNICO',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme', 'Não Aplicável'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA SOLDA SUPORTES CALÇO MECÂNICO',
    },
    {
      codigo: 'CQ37-B',
      descricao: 'VERIFICAR SE PARAFUSOS QUE SEGURAM A CALHA ESTÃO NA POSIÇÃO',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Posição; Quantidade de parafusos',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Conforme desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DOS PARAFUSOS QUE SEGURAM A CALHA',
    },
    {
      codigo: 'CQ38-B',
      descricao: 'MONTAGEM PISO',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Deformações; Ondulações no piso',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Conforme o desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA MONTAGEM PISO',
    },
    {
      codigo: 'CQ39-B',
      descricao: 'SOLDA PISO',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA SOLDA PISO',
    },
    {
      codigo: 'CQ40-B',
      descricao: 'POSICIONAMENTO DE TRILHOS',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Esquadro',
      metodoVerificacao: 'Dimensional',
      instrumento: 'Esquadro',
      criteriosAceitacao: 'Conforme desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DO POSICIONAMENTO DE TRILHOS',
    },
    {
      codigo: 'CQ41-B',
      descricao: 'SOLDA TRILHOS',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA SOLDA TRILHOS',
    },
    {
      codigo: 'CQ42-B',
      descricao: 'POSICIONAMENTO TRAVA CINTAS (ETAPA 3 COD. 20137 E 26299)',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'N/A',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Conforme desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DO POSICIONAMENTO TRAVA CINTAS',
    },
    {
      codigo: 'CQ43-B',
      descricao: 'SOLDA TRAVA CINTAS',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA SOLDA TRAVA CINTAS',
    },
  ],
};

// ============================================================================
// CQ-C: CENTRAL HIDRÁULICA (SETOR HIDRÁULICA)
// ============================================================================
export const CQ_C_CENTRAL_HIDRAULICA: CQSetor = {
  codigo: 'C',
  nome: 'CENTRAL HIDRÁULICA (SETOR HIDRÁULICA)',
  processo: 'C - CENTRAL HIDRÁULICA (SETOR HIDRÁULICA)',
  perguntas: [
    {
      codigo: 'CQ1-C',
      descricao: 'MOTOR LIVRE COM PESO DA BOMBA',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Ventoinha',
      metodoVerificacao: 'Funcional (verificar se ventoinha está trancada; girar ventoinha com a mão)',
      instrumento: 'N/A',
      criteriosAceitacao: 'Ventoinha girar',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ2-C',
      descricao: 'VERIFICAR ACOPLAMENTO DOS MOTORES',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Distância do acoplamento de um lado para o outro',
      metodoVerificacao: 'Dimensional',
      instrumento: 'Trena',
      criteriosAceitacao: '+/- 1 mm',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ3-C',
      descricao: 'VERIFICAR ADAPTADORES DOS BLOCOS',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'N/A',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Conforme desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DOS ADAPTADORES DOS BLOCOS',
    },
    {
      codigo: 'CQ4-C',
      descricao: 'ASPECTO VISUAL DAS MANGUEIRAS',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Integridade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Íntegro',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DAS MANGUEIRAS',
    },
    {
      codigo: 'CQ5-C',
      descricao: 'APERTO DAS CONEXÕES DAS MANGUEIRAS',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'N/A',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Conexões firmes',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DO APERTO DAS CONEXÕES',
    },
    {
      codigo: 'CQ6-C',
      descricao: 'INSPECIONAR VISOR DE NÍVEL',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Vedação',
      metodoVerificacao: 'Visual (verificar se tem vedação de borracha)',
      instrumento: 'N/A',
      criteriosAceitacao: 'Com vedação de borracha',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DO VISOR DE NÍVEL',
    },
    {
      codigo: 'CQ7-C',
      descricao: 'INSPECIONAR MONTAGEM ELÉTRICA DE FORÇA',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Ligação elétrica do motor',
      metodoVerificacao: 'Visual (verificar ligações elétricas)',
      instrumento: 'N/A',
      criteriosAceitacao: 'Conforme desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA MONTAGEM ELÉTRICA DE FORÇA',
    },
    {
      codigo: 'CQ8-C',
      descricao: 'LIMPEZA GERAL / GRAXA / POEIRAS / MARCAS',
      etapa: 'LIMPEZA',
      avaliacao: '100%',
      medidaCritica: 'Limpo; Graxa; Poeira; Marcas',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Limpo; Sem graxa; Sem poeira; Sem marcas',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA LIMPEZA GERAL',
    },
    {
      codigo: 'CQ9-C',
      descricao: 'ALINHAMENTO DE COMPONENTES MONTADOS',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Alinhamento',
      metodoVerificacao: 'Visual',
      instrumento: 'Visual',
      criteriosAceitacao: 'Componentes alinhados',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DO ALINHAMENTO DE COMPONENTES',
    },
    {
      codigo: 'CQ10-C',
      descricao: 'PONTO DE ATERRAMENTO NOS MOTORES',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Aterramento dos motores',
      metodoVerificacao: 'Visual (certificar se foi realizada a ligação do aterramento no motor)',
      instrumento: 'N/A',
      criteriosAceitacao: 'Ligação de aterramento realizada',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DO PONTO DE ATERRAMENTO',
    },
    {
      codigo: 'CQ11-C',
      descricao: 'MOTORES ADEQUADOS À TENSÃO E FREQUÊNCIA FORNECIDAS PELO CLIENTE',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Tensão; Frequência',
      metodoVerificacao: 'Visual (verificar as placas dos motores)',
      instrumento: 'N/A',
      criteriosAceitacao: 'Conforme especificado na reunião de START',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DAS PLACAS DOS MOTORES',
    },
    {
      codigo: 'CQ12-C',
      descricao: 'CIRCUITO HIDRÁULICO CONFORME O PROJETO',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Circuito hidráulico',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Conforme desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DO CIRCUITO HIDRÁULICO',
    },
    {
      codigo: 'CQ13-C',
      descricao: 'APERTO DA MANGUEIRA INTERNA DO CONJUNTO FLANGE/MOTOR/BOMBA',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Aperto da mangueira interna',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Mangueira apertada',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DO APERTO DA MANGUEIRA INTERNA',
    },
    {
      codigo: 'CQ14-C',
      descricao: 'APERTO DO TAMPÃO DO DRENO',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Aperto do tampão do dreno',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Tampão apertado',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DO APERTO DO TAMPÃO DO DRENO',
    },
    {
      codigo: 'CQ15-C',
      descricao: 'VERIFICAR APLICAÇÃO DO ÓLEO PROTETIVO NA PARTE INTERNA DA CENTRAL',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Aplicação do óleo protetivo',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Óleo protetivo aplicado',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA APLICAÇÃO DO ÓLEO PROTETIVO',
    },
  ],
};

// ============================================================================
// CQ-D: SOLDA LADO 01
// ============================================================================
export const CQ_D_SOLDA_LADO_01: CQSetor = {
  codigo: 'D',
  nome: 'SOLDA LADO 01',
  processo: 'D - SOLDA LADO 01',
  perguntas: [
    {
      codigo: 'CQ1-D',
      descricao: 'REFORÇOS EMENDA DAS VIGAS',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Reforços no esquadro',
      metodoVerificacao: 'Dimensional',
      instrumento: 'Trena; Esquadro',
      criteriosAceitacao: 'Reforços nas emendas das vigas',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ2-D',
      descricao: 'SOLDA REFORÇOS VIGAS',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA SOLDA REFORÇOS VIGAS',
    },
    {
      codigo: 'CQ3-D',
      descricao: 'REFORÇOS TRAVA CINTAS (CONFORME DESENHO ETAPA 3)',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Reforços no esquadro',
      metodoVerificacao: 'Dimensional',
      instrumento: 'Trena; Esquadro',
      criteriosAceitacao: 'Reforços no esquadro',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ4-D',
      descricao: 'SOLDA REFORÇOS TRAVA CINTAS',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA SOLDA REFORÇOS TRAVA CINTAS',
    },
    {
      codigo: 'CQ5-D',
      descricao: 'SOLDA CAIXA TRAVA CHASSI 24569',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA SOLDA CAIXA TRAVA CHASSI',
    },
    {
      codigo: 'CQ6-D',
      descricao: 'SOLDA TRAVA RODAS E ENCAIXE DOS CILINDROS',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA SOLDA TRAVA RODAS E ENCAIXE DOS CILINDROS',
    },
    {
      codigo: 'CQ7-D',
      descricao: 'POSICIONAMENTO BATENTE DE DESCIDA',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Posição do batente',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Conforme desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DO POSICIONAMENTO BATENTE DE DESCIDA',
    },
    {
      codigo: 'CQ8-D',
      descricao: 'SOLDA BATENTE DE DESCIDA',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA SOLDA BATENTE DE DESCIDA',
    },
    {
      codigo: 'CQ9-D',
      descricao: 'SOLDA GRAMPOS E BARRA REDONDAS',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA SOLDA GRAMPOS E BARRA REDONDAS',
    },
    {
      codigo: 'CQ10-D',
      descricao: 'SOLDA FECHAMENTO FRONTAL GRADEADO (24845)',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme', 'Não Aplicável'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA SOLDA FECHAMENTO FRONTAL GRADEADO',
    },
    {
      codigo: 'CQ11-D',
      descricao: 'SOLDA DA BARRA CHATA NO LAVRADO',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA SOLDA DA BARRA CHATA NO LAVRADO',
    },
    {
      codigo: 'CQ12-D',
      descricao: 'SOLDA REFORÇO TRANSVERSAL PARA ASSOALHO',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA SOLDA REFORÇO TRANSVERSAL',
    },
    {
      codigo: 'CQ13-D',
      descricao: 'SOLDA CHAPA 1050 X 3000',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA SOLDA CHAPA 1050 X 3000',
    },
    {
      codigo: 'CQ14-D',
      descricao: 'SOLDA PISO',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA SOLDA PISO',
    },
    {
      codigo: 'CQ15-D',
      descricao: 'SOLDA EMENDA VIGAS',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA SOLDA EMENDA VIGAS',
    },
    {
      codigo: 'CQ16-D',
      descricao: 'CHAPA DE FECHAMENTO DIANTEIRA',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA CHAPA DE FECHAMENTO DIANTEIRA',
    },
    {
      codigo: 'CQ17-D',
      descricao: 'CHAPA DE FECHAMENTO TRASEIRA',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA CHAPA DE FECHAMENTO TRASEIRA',
    },
  ],
};

// ============================================================================
// CQ-E: SOLDA LADO 02
// ============================================================================
export const CQ_E_SOLDA_LADO_02: CQSetor = {
  codigo: 'E',
  nome: 'SOLDA LADO 02',
  processo: 'E - SOLDA LADO 02',
  perguntas: [
    {
      codigo: 'CQ1-E',
      descricao: 'REFORÇOS EMENDA DAS VIGAS',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Esquadro',
      metodoVerificacao: 'Dimensional',
      instrumento: 'Trena; Esquadro',
      criteriosAceitacao: 'No esquadro',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ2-E',
      descricao: 'SOLDA REFORÇOS VIGAS',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA SOLDA REFORÇOS VIGAS',
    },
    {
      codigo: 'CQ3-E',
      descricao: 'REFORÇOS TRAVA CINTAS (CONFORME DESENHO ETAPA 3)',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DOS REFORÇOS TRAVA CINTAS',
    },
    {
      codigo: 'CQ4-E',
      descricao: 'SOLDA REFORÇOS TRAVA CINTAS',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA SOLDA REFORÇOS TRAVA CINTAS',
    },
    {
      codigo: 'CQ5-E',
      descricao: 'SOLDA CAIXA TRAVA CHASSI Cód.24569',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA SOLDA CAIXA TRAVA CHASSI',
    },
    {
      codigo: 'CQ6-E',
      descricao: 'SOLDA TRAVA RODAS',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA SOLDA TRAVA RODAS',
    },
    {
      codigo: 'CQ7-E',
      descricao: 'POSICIONAMENTO BATENTE DE DESCIDA',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Posicionamento do batente',
      metodoVerificacao: 'Dimensional',
      instrumento: 'Trena',
      criteriosAceitacao: 'Conforme desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ8-E',
      descricao: 'SOLDA BATENTE DE DESCIDA',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA SOLDA BATENTE DE DESCIDA',
    },
    {
      codigo: 'CQ9-E',
      descricao: 'SOLDA GRAMPOS E BARRA REDONDAS',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM SOLDA GRAMPOS E BARRA REDONDAS',
    },
    {
      codigo: 'CQ10-E',
      descricao: 'SOLDA FECHAMENTO FRONTAL GRADEADO',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA SOLDA FECHAMENTO FRONTAL GRADEADO',
    },
    {
      codigo: 'CQ11-E',
      descricao: 'SOLDA DA BARRA CHATA NO LAVRADO',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA SOLDA DA BARRA CHATA NO LAVRADO',
    },
    {
      codigo: 'CQ12-E',
      descricao: 'SOLDA GRAMPOS E BARRAS REDONDA',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA SOLDA GRAMPOS E BARRAS REDONDA',
    },
    {
      codigo: 'CQ13-E',
      descricao: 'SOLDA REFORÇO TRANSVERSAL PARA ASSOALHO',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA SOLDA REFORÇO TRANSVERSAL PARA ASSOALHO',
    },
    {
      codigo: 'CQ14-E',
      descricao: 'SOLDA DO REFORÇO DO PISO',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA SOLDA DO REFORÇO DO PISO',
    },
    {
      codigo: 'CQ15-E',
      descricao: 'SOLDA CHAPA 1050 X 3000',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA SOLDA CHAPA 1050 X 3000',
    },
    {
      codigo: 'CQ16-E',
      descricao: 'SOLDA PISO',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA SOLDA PISO',
    },
    {
      codigo: 'CQ17-E',
      descricao: 'SOLDA EMENDA VIGAS',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA SOLDA EMENDA VIGAS',
    },
    {
      codigo: 'CQ18-E',
      descricao: 'CHAPA DE FECHAMENTO DIANTEIRA',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA CHAPA DE FECHAMENTO DIANTEIRA',
    },
    {
      codigo: 'CQ19-E',
      descricao: 'CHAPA DE FECHAMENTO TRASEIRA',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: true,
      imagemDescricao: 'ANEXAR IMAGEM DA CHAPA DE FECHAMENTO TRASEIRA',
    },
  ],
};

// ============================================================================
// CQ-F: MONTAGEM E SOLDA INFERIOR
// ============================================================================
export const CQ_F_MONTAGEM_SOLDA_INFERIOR: CQSetor = {
  codigo: 'F',
  nome: 'MONTAGEM E SOLDA INFERIOR',
  processo: 'F - MONTAGEM E SOLDA INFERIOR',
  perguntas: [
    {
      codigo: 'CQ1-F',
      descricao: 'EMENDA DAS VIGAS INFERIORES',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ2-F',
      descricao: 'MONTAGEM REFORÇOS INFERIORES',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Posição dos reforços inferiores',
      metodoVerificacao: 'Dimensional',
      instrumento: 'Trena',
      criteriosAceitacao: 'Conforme desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ3-F',
      descricao: 'REFORÇOS INFERIORES',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ4-F',
      descricao: 'SOLDA PISO',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ5-F',
      descricao: 'MONTAGEM E FECHAMENTO 690 MM CONFORME DESENHO',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'N/A',
      metodoVerificacao: 'N/A',
      instrumento: 'N/A',
      criteriosAceitacao: 'Conforme desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ6-F',
      descricao: 'SOLDA FECHAMENTO 690 MM GRADEADO',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'N/A',
      metodoVerificacao: 'N/A',
      instrumento: 'N/A',
      criteriosAceitacao: 'Conforme desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ7-F',
      descricao: 'MONTAGEM TAMPA DE INSPEÇÃO',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'N/A',
      metodoVerificacao: 'N/A',
      instrumento: 'N/A',
      criteriosAceitacao: 'Conforme desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ8-F',
      descricao: 'SUPORTE TAMPA DE INSPEÇÃO',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'N/A',
      metodoVerificacao: 'N/A',
      instrumento: 'N/A',
      criteriosAceitacao: 'Conforme desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ9-F',
      descricao: 'SOLDA EMENDA DAS VIGAS SUPERIORES',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'N/A',
      metodoVerificacao: 'N/A',
      instrumento: 'N/A',
      criteriosAceitacao: 'Conforme desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ10-F',
      descricao: 'PERFIL ASSOALHO',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ11-F',
      descricao: 'MONTAGEM SAPATA CILINDRO PRINCIPAL',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Posição da sapata',
      metodoVerificacao: 'Dimensional',
      instrumento: 'Trena',
      criteriosAceitacao: 'Conforme desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ12-F',
      descricao: 'SAPATA CILINDRO PRINCIPAL',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ13-F',
      descricao: 'SOLDA REFORÇO TRAVA CINTAS',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
  ],
};

// ============================================================================
// CQ-G: MONTAGEM ELÉTRICA/HIDRÁULICO
// ============================================================================
export const CQ_G_MONTAGEM_ELETRICA_HIDRAULICO: CQSetor = {
  codigo: 'G',
  nome: 'MONTAGEM ELÉTRICA/HIDRÁULICO',
  processo: 'G - MONTAGEM ELÉTRICA/HIDRÁULICO',
  perguntas: [
    {
      codigo: 'CQ1-G',
      descricao: 'FURAÇÃO PARA PASSAGEM DE MANGUEIRAS E ELÉTRICAS',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Posição dos furos',
      metodoVerificacao: 'Dimensional',
      instrumento: 'Trena',
      criteriosAceitacao: 'Conforme desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ2-G',
      descricao: 'SOLDA CHAPINHAS DE ACABAMENTO NOS FUROS DA VIGA',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ3-G',
      descricao: 'PARAFUSOS PARA PRENDER MANGUEIRA',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Presença dos parafusos',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Conforme desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ4-G',
      descricao: 'SOLDA PARA PRENDER MANGUEIRA',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ5-G',
      descricao: 'SUPORTE PARA VÁLVULAS TRAVA PINO',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Posição do suporte',
      metodoVerificacao: 'Dimensional',
      instrumento: 'Trena',
      criteriosAceitacao: 'Conforme desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ6-G',
      descricao: 'SUPORTE PARA VÁLVULAS LATERAIS',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Posição do suporte',
      metodoVerificacao: 'Dimensional',
      instrumento: 'Trena',
      criteriosAceitacao: 'Conforme desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ7-G',
      descricao: 'MONTAGEM DO PISO (ABERTO)',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Posição do piso',
      metodoVerificacao: 'Dimensional',
      instrumento: 'Trena',
      criteriosAceitacao: 'Conforme desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ8-G',
      descricao: 'MONTAGEM DO PISO (FECHADO)',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Posição do piso',
      metodoVerificacao: 'Dimensional',
      instrumento: 'Trena',
      criteriosAceitacao: 'Conforme desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ9-G',
      descricao: 'TESTAR MOVIMENTAÇÃO DA TAMPA DE INSPEÇÃO DO TRAVA RODA',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Movimento da tampa',
      metodoVerificacao: 'Funcional',
      instrumento: 'N/A',
      criteriosAceitacao: 'Tampa se movimentar',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ10-G',
      descricao: 'SUPORTE TAMPA DE INSPEÇÃO',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ11-G',
      descricao: 'LOCALIZAÇÃO DO SUPORTE DA VÁLVULA TRAVA RODA',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Localização do suporte',
      metodoVerificacao: 'Dimensional',
      instrumento: 'Trena',
      criteriosAceitacao: 'Conforme desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ12-G',
      descricao: 'VERIFICAR VÁLVULA LATERAL',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Posição da válvula',
      metodoVerificacao: 'Dimensional',
      instrumento: 'Trena',
      criteriosAceitacao: 'Conforme desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ13-G',
      descricao: 'MONTAGEM CHAPA INCLINOSTATO DO TOMBADOR COM FECHAMENTO INFERIOR',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Posição da chapa do inclinostato',
      metodoVerificacao: 'Dimensional',
      instrumento: 'Trena',
      criteriosAceitacao: 'Conforme desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ14-G',
      descricao: 'MONTAGEM CHAPA INCLINOSTATO DO TOMBADOR SEM FECHAMENTO INFERIOR',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Posição da chapa do inclinostato',
      metodoVerificacao: 'Dimensional',
      instrumento: 'Trena',
      criteriosAceitacao: 'Conforme desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ15-G',
      descricao: 'MONTAGEM DAS ABRAÇADEIRAS TIPO D',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Posição das abraçadeiras',
      metodoVerificacao: 'Dimensional',
      instrumento: 'Trena',
      criteriosAceitacao: 'Conforme desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ16-G',
      descricao: 'MONTAGEM DOS SUPORTES DA CAIXA ELÉTRICA LATERAL',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Posição dos suportes',
      metodoVerificacao: 'Dimensional',
      instrumento: 'Trena',
      criteriosAceitacao: 'Conforme desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ17-G',
      descricao: 'MONTAGEM DOS SUPORTES DA CAIXA ELÉTRICA DOS SENSORES DAS TRAVAS (INTERNO)',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Posição dos suportes',
      metodoVerificacao: 'Dimensional',
      instrumento: 'Trena',
      criteriosAceitacao: 'Conforme desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ18-G',
      descricao: 'MONTAGEM DO SUPORTE DO SENSOR TRAVA RODA',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Suporte do sensor',
      metodoVerificacao: 'Funcional (realizar teste de colisão)',
      instrumento: 'N/A',
      criteriosAceitacao: 'Conforme POP',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
  ],
};

// ============================================================================
// CQ-H: MONTAGEM DAS CALHAS
// ============================================================================
export const CQ_H_MONTAGEM_CALHAS: CQSetor = {
  codigo: 'H',
  nome: 'MONTAGEM DAS CALHAS',
  processo: 'H - MONTAGEM DAS CALHAS',
  perguntas: [
    {
      codigo: 'CQ1-H',
      descricao: 'MONTAGEM CONJUNTO MOD 1',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Posição do conjunto',
      metodoVerificacao: 'Dimensional',
      instrumento: 'Trena',
      criteriosAceitacao: 'Conforme desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ2-H',
      descricao: 'SOLDA MOD 1',
      etapa: 'SOLDA',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ3-H',
      descricao: 'MONTAGEM CONJUNTO MOD 2',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Posição do conjunto',
      metodoVerificacao: 'Dimensional',
      instrumento: 'Trena',
      criteriosAceitacao: 'Conforme desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ4-H',
      descricao: 'SOLDA MOD 2',
      etapa: 'SOLDA',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ5-H',
      descricao: 'MONTAGEM CONJUNTO MOD 3',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Posição do conjunto',
      metodoVerificacao: 'Dimensional',
      instrumento: 'Trena',
      criteriosAceitacao: 'Conforme desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ6-H',
      descricao: 'SOLDA MOD 3',
      etapa: 'SOLDA',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ7-H',
      descricao: 'MONTAGEM CONJUNTO MOD 4',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Posição do conjunto',
      metodoVerificacao: 'Dimensional',
      instrumento: 'Trena',
      criteriosAceitacao: 'Conforme desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ8-H',
      descricao: 'SOLDA MOD 4',
      etapa: 'SOLDA',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ9-H',
      descricao: 'MONTAGEM CONJUNTO MOD 5 CONFORME PROJETO (30 M)',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Posição do conjunto',
      metodoVerificacao: 'Dimensional',
      instrumento: 'Trena',
      criteriosAceitacao: 'Conforme desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ10-H',
      descricao: 'SOLDA MOD 5',
      etapa: 'SOLDA',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
  ],
};

// ============================================================================
// CQ-I: TRAVADOR DE RODAS LATERAL MÓVEL
// ============================================================================
export const CQ_I_TRAVADOR_RODAS_LATERAL: CQSetor = {
  codigo: 'I',
  nome: 'TRAVADOR DE RODAS LATERAL MÓVEL',
  processo: 'I - TRAVADOR DE RODAS LATERAL MÓVEL',
  perguntas: [
    {
      codigo: 'CQ1-I',
      descricao: 'PRESSÃO DE ABERTURA LATERAL DO CILINDRO (NÃO PASSAR DE 30 BAR)',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Pressão de abertura',
      metodoVerificacao: 'Dimensional',
      instrumento: 'Barômetro',
      criteriosAceitacao: '30 BAR +/- 10 BAR',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ2-I',
      descricao: 'REGULAGEM DA PRESSÃO DA VÁLVULA DE ALÍVIO ABERTURA LATERAL DO CILINDRO',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Pressão das válvula',
      metodoVerificacao: 'Dimensional',
      instrumento: 'Barômetro',
      criteriosAceitacao: '30 BAR +/- 10 BAR',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ3-I',
      descricao: 'REGULAGEM DO PRESSOSTATO DE TRAÇÃO DO CILINDRO PRINCIPAL (55 BAR)',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Regulagem do pressostato',
      metodoVerificacao: 'Dimensional',
      instrumento: 'Barômetro',
      criteriosAceitacao: '55 BAR +/- 10 BAR',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ4-I',
      descricao: 'REGULAGEM DE TRAÇÃO DO CILINDRO PRINCIPAL (65 BAR)',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Regulagem de tração',
      metodoVerificacao: 'Dimensional',
      instrumento: 'Barômetro',
      criteriosAceitacao: '65 BAR +/- 10 BAR',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ5-I',
      descricao: 'TESTE PRESSÃO VÁLVULA DE RETENÇÃO',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Pressão da válvula',
      metodoVerificacao: 'Dimensional',
      instrumento: 'Barômetro',
      criteriosAceitacao: 'Conforme projeto',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ6-I',
      descricao: 'TESTE DE FUNCIONAMENTO DA ESTEIRA',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Funcionamento da esteira',
      metodoVerificacao: 'Funcional',
      instrumento: 'N/A',
      criteriosAceitacao: 'Esteira operar',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ7-I',
      descricao: 'APERTO PARAFUSO ALLEN DA ASTE PRINCIPAL',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Aperto do parafuso',
      metodoVerificacao: 'Dimensional',
      instrumento: 'Torquímetro',
      criteriosAceitacao: 'Conforme projeto',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ8-I',
      descricao: 'LUBRIFICAR GRAXEIRA ASTE PRINCIPAL',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Lubrificação da graxeta',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Graxeta lubrificada',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ9-I',
      descricao: 'LUBRIFICAR GRAXEIRA ASTE PRINCIPAL',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Lubrificação da graxeta',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Graxeta lubrificada',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ10-I',
      descricao: 'LUBRIFICAÇÃO DO MUNHÃO DO CILINDRO PRINCIPAL',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Lubrificação do munhão',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Munhão lubrificado',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ11-I',
      descricao: 'APERTO PARAFUSO DO OLHAIS DO MUNHÃO DO CILINDRO PRINCIPAL',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Aperto do parafuso',
      metodoVerificacao: 'Dimensional',
      instrumento: 'Torquímetro',
      criteriosAceitacao: 'Conforme projeto',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ12-I',
      descricao: 'APERTO PARAFUSO DA ESTEIRA REGULAGEM DE APERTO DAS GUIAS INFERIORES DE NAYLON, INSTALAÇÃO DE CONTRAPORCAS',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Aperto do parafuso',
      metodoVerificacao: 'Dimensional',
      instrumento: 'Torquímetro',
      criteriosAceitacao: 'Conforme projeto',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ13-I',
      descricao: 'PARAFUSO DO OLHAL DO CILINDRO PRINCIPAL',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Aperto do parafuso',
      metodoVerificacao: 'Dimensional',
      instrumento: 'Torquímetro',
      criteriosAceitacao: 'Conforme projeto',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ14-I',
      descricao: 'VERIFICAR PASSAGEM DOS PINOS DE FIXAÇÃO NA PLATAFORMA',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Passagem dos pinos',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Conforme desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ15-I',
      descricao: 'ACABAMENTO DAS SOLDAS',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Respingos',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem respingos',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ16-I',
      descricao: 'ACABAMENTO DE PINTURA',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Escorrimento; Cobertura',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Conforme projeto',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ17-I',
      descricao: 'VERIFICAR CONDIÇÕES FÍSICAS DA HASTE DO CILINDRO',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Condições físicas',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem danos',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ18-I',
      descricao: 'VERIFICAR SE A HASTE DO CILINDRO ESTÁ RECOLHIDA PARA TRANSPORTE',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Haste do cilindro',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Haste recolhida',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
  ],
};

// ============================================================================
// CQ-J: CAIXA DO TRAVA CHASSI
// ============================================================================
export const CQ_J_CAIXA_TRAVA_CHASSI: CQSetor = {
  codigo: 'J',
  nome: 'CAIXA DO TRAVA CHASSI',
  processo: 'J - CAIXA DO TRAVA CHASSI',
  perguntas: [
    {
      codigo: 'CQ1-J',
      descricao: 'CAIXA TRAVA CHASSI (MONTADA NA PLATAFORMA)',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Posição do trava chassi',
      metodoVerificacao: 'Dimensional',
      instrumento: 'Trena',
      criteriosAceitacao: 'Conforme desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ2-J',
      descricao: 'SOLDA CAIXA TRAVA CHASSI',
      etapa: 'SOLDA',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
  ],
};

// ============================================================================
// CQ-K: TRAVA CHASSI
// ============================================================================
export const CQ_K_TRAVA_CHASSI: CQSetor = {
  codigo: 'K',
  nome: 'TRAVA CHASSI',
  processo: 'K - TRAVA CHASSI',
  perguntas: [
    {
      codigo: 'CQ1-K',
      descricao: 'VERIFICAR MEDIDA INTERNA DA CAIXA TRAVA CHASSI',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Posição do trava chassi',
      metodoVerificacao: 'Dimensional',
      instrumento: 'Trena',
      criteriosAceitacao: 'Conforme desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ2-K',
      descricao: 'TESTAR PINO DO CILINDRO',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Funcionamento do pino',
      metodoVerificacao: 'Funcional',
      instrumento: 'N/A',
      criteriosAceitacao: 'Pino funcionar',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ3-K',
      descricao: 'PARAFUSOS ESTÃO FIXADOS',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Parafusos fixados',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Parafusos fixados',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ4-K',
      descricao: 'SOLDA CAVALETE TRAVA CHASSI',
      etapa: 'SOLDA',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
  ],
};

// ============================================================================
// CQ-L: CAVALETE DO TRAVA CHASSI
// ============================================================================
export const CQ_L_CAVALETE_TRAVA_CHASSI: CQSetor = {
  codigo: 'L',
  nome: 'CAVALETE DO TRAVA CHASSI',
  processo: 'L - CAVALETE DO TRAVA CHASSI',
  perguntas: [
    {
      codigo: 'CQ1-L',
      descricao: 'MONTAGEM CAVALETE',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Montagem do cavalete',
      metodoVerificacao: 'Dimensional',
      instrumento: 'Trena',
      criteriosAceitacao: 'Conforme desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ2-L',
      descricao: 'TESTAR PINO DO CILINDRO',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Funcionamento do pino',
      metodoVerificacao: 'Funcional',
      instrumento: 'N/A',
      criteriosAceitacao: 'Pino funcionar',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ3-L',
      descricao: 'PARAFUSOS ESTÃO FIXADOS',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Parafusos fixados',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Parafusos fixados',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ4-L',
      descricao: 'SOLDA CAVALETE TRAVA CHASSI',
      etapa: 'SOLDA',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ5-L',
      descricao: 'PINTURA DO CAVALETE',
      etapa: 'PINTURA',
      avaliacao: '100%',
      medidaCritica: 'Escorrimento; Cobertura',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Conforme projeto',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
  ],
};

// ============================================================================
// CQ-M: CENTRAL HIDRÁULICA SETOR SUBCONJUNTOS
// ============================================================================
export const CQ_M_CENTRAL_HIDRAULICA_SUBCONJUNTOS: CQSetor = {
  codigo: 'M',
  nome: 'CENTRAL HIDRÁULICA SETOR SUBCONJUNTOS',
  processo: 'M - CENTRAL HIDRÁULICA SETOR SUBCONJUNTOS',
  perguntas: [
    {
      codigo: 'CQ1-M',
      descricao: 'MONTAGEM DO RESERVATÓRIO',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Montagem do reservatório',
      metodoVerificacao: 'Dimensional',
      instrumento: 'Trena',
      criteriosAceitacao: 'Conforme desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ2-M',
      descricao: 'OLHAL DE IÇAMENTO',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Posição do olhal',
      metodoVerificacao: 'Dimensional',
      instrumento: 'Trena',
      criteriosAceitacao: 'Conforme desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ3-M',
      descricao: 'MONTAGEM VISOR DE NÍVEL',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Montagem do visor',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Conforme projeto',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ4-M',
      descricao: 'VERIFICAR MONTAGEM E ESQUADRO DO RESERVATÓRIO',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Montagem do esquadro',
      metodoVerificacao: 'Dimensional',
      instrumento: 'Trena; Esquadro',
      criteriosAceitacao: 'Conforme desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ5-M',
      descricao: 'MONTAGEM DAS CHICANAS',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Montagem das chicanas',
      metodoVerificacao: 'Dimensional',
      instrumento: 'Trena',
      criteriosAceitacao: 'Conforme desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ6-M',
      descricao: 'PARTE INTERNA JANELA DE INSPEÇÃO',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Montagem parte interna',
      metodoVerificacao: 'Visual (verificar encaixe da cruzeta)',
      instrumento: 'N/A',
      criteriosAceitacao: 'Cruzeta encaixada',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ7-M',
      descricao: 'VERIFICAR A QUALIDADE DA SOLDA INTERNA DO RESERVATÓRIO',
      etapa: 'SOLDA',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ8-M',
      descricao: 'FLANGE 3 CV',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Posição do flange',
      metodoVerificacao: 'Dimensional',
      instrumento: 'Trena',
      criteriosAceitacao: 'Conforme desenho',
      opcoes: ['Conforme', 'Não conforme', 'Não Aplicável'],
      requerImagem: false,
    },
    {
      codigo: 'CQ9-M',
      descricao: 'FLANGE 4 CV',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Posição do flange',
      metodoVerificacao: 'Dimensional',
      instrumento: 'Trena',
      criteriosAceitacao: 'Conforme desenho',
      opcoes: ['Conforme', 'Não conforme', 'Não Aplicável'],
      requerImagem: false,
    },
    {
      codigo: 'CQ10-M',
      descricao: 'FLANGE 10 / 15 CV',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Posição do flange',
      metodoVerificacao: 'Dimensional',
      instrumento: 'Trena',
      criteriosAceitacao: 'Conforme desenho',
      opcoes: ['Conforme', 'Não conforme', 'Não Aplicável'],
      requerImagem: false,
    },
    {
      codigo: 'CQ11-M',
      descricao: 'FLANGE 20 / 25 / 30 CV',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Posição do flange',
      metodoVerificacao: 'Dimensional',
      instrumento: 'Trena',
      criteriosAceitacao: 'Conforme desenho',
      opcoes: ['Conforme', 'Não conforme', 'Não Aplicável'],
      requerImagem: false,
    },
    {
      codigo: 'CQ12-M',
      descricao: 'FLANGE 50 CV',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Posição do flange',
      metodoVerificacao: 'Dimensional',
      instrumento: 'Trena',
      criteriosAceitacao: 'Conforme desenho',
      opcoes: ['Conforme', 'Não conforme', 'Não Aplicável'],
      requerImagem: false,
    },
    {
      codigo: 'CQ13-M',
      descricao: 'VERIFICAR LIMPEZA INTERNA DO RESERVATÓRIO, ANTES DE COLOCAR A TAMPA',
      etapa: 'LIMPEZA',
      avaliacao: '100%',
      medidaCritica: 'Limpeza interna do reservatório',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Reservatório limpo',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ14-M',
      descricao: 'VERIFICAR A CORRETA MONTAGEM DOS COMPONENTES NA TAMPA',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Posição dos componentes da tampa',
      metodoVerificacao: 'Dimensional',
      instrumento: 'Trena',
      criteriosAceitacao: 'Conforme desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ15-M',
      descricao: 'VERIFICAR ALINHAMENTO DOS PARAFUSOS DO FLANGE',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Posição dos componentes da tampa',
      metodoVerificacao: 'Dimensional',
      instrumento: 'Trena',
      criteriosAceitacao: 'Conforme desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ16-M',
      descricao: 'PARTE INFERIOR DA TAMPA (SOLDAGEM DOS TUBOS)',
      etapa: 'SOLDA',
      avaliacao: '100%',
      medidaCritica: 'Trinca; Porosidade',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem trinca; Sem porosidade',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ17-M',
      descricao: 'TESTE DE FALHA DE SOLDA LP (LÍQUIDO PENETRANTE)',
      etapa: 'SOLDA',
      avaliacao: '100%',
      medidaCritica: 'Penetração',
      metodoVerificacao: 'Funcional',
      instrumento: 'N/A',
      criteriosAceitacao: 'Solda com penetração suficiente',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
  ],
};

// ============================================================================
// CQ-N: PAINEL ELÉTRICO
// ============================================================================
export const CQ_N_PAINEL_ELETRICO: CQSetor = {
  codigo: 'N',
  nome: 'PAINEL ELÉTRICO',
  processo: 'N - PAINEL ELÉTRICO',
  perguntas: [
    {
      codigo: 'CQ1-N',
      descricao: 'CONDIÇÕES FÍSICAS DA CAIXA',
      etapa: 'MONTAGEM',
      avaliacao: '100%',
      medidaCritica: 'Desplacamento',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem desplacamento',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ2-N',
      descricao: 'INEXISTÊNCIA DE FIOS SOLTOS',
      etapa: 'MONTAGEM',
      avaliacao: 'Total',
      medidaCritica: 'Fios soltos',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Testar por amostragem (20 fios de comando e 3 fios força)',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ3-N',
      descricao: 'LAYOUT',
      etapa: 'MONTAGEM',
      avaliacao: 'Total',
      medidaCritica: 'Layout',
      metodoVerificacao: 'Visual (conforme desenho interno e externo)',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem tolerância',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ4-N',
      descricao: 'IDENTIFICAÇÃO DE TODOS OS FIOS',
      etapa: 'MONTAGEM',
      avaliacao: 'Total',
      medidaCritica: 'Identificação dos fios',
      metodoVerificacao: 'Visual e verificar numeração',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem tolerância',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ5-N',
      descricao: 'IDENTIFICAÇÃO DOS BORNERS RELÉ',
      etapa: 'MONTAGEM',
      avaliacao: 'Total',
      medidaCritica: 'Identificação dos borners',
      metodoVerificacao: 'Visual e verificar numeração',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem tolerância',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ6-N',
      descricao: 'IDENTIFICAÇÃO DOS BORNES',
      etapa: 'MONTAGEM',
      avaliacao: 'Total',
      medidaCritica: 'Identificação dos bornes',
      metodoVerificacao: 'Visual e verificar numeração',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem tolerância',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ7-N',
      descricao: 'FUROS COM PRENSA CABOS OU SIMILARES',
      etapa: 'MONTAGEM',
      avaliacao: 'Total',
      medidaCritica: 'Furos',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem tolerância e conforme desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ8-N',
      descricao: 'VEDAÇÃO DA TAMPA',
      etapa: 'MONTAGEM',
      avaliacao: 'Total',
      medidaCritica: 'Vedação',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem tolerância e conforme desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ9-N',
      descricao: 'ADESIVO DOS BOTÕES COM IDENTIFICAÇÃO E ALINHAMENTO',
      etapa: 'MONTAGEM',
      avaliacao: 'Total',
      medidaCritica: 'Adesivo dos botões',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem tolerância e conforme desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ10-N',
      descricao: 'CONTROLE REMOTO COM PILHAS DENTRO DO PAINEL',
      etapa: 'MONTAGEM',
      avaliacao: 'Total',
      medidaCritica: 'Controle remoto com pilhas',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem tolerância',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ11-N',
      descricao: 'CAPA DE SILICONE NOS BOTÕES',
      etapa: 'MONTAGEM',
      avaliacao: 'Total',
      medidaCritica: 'Capa de silicone',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem tolerância',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ12-N',
      descricao: 'VERIFICAR SE AS PROTEÇÕES DA SOFTSTARTER ESTÃO LIGADAS',
      etapa: 'MONTAGEM',
      avaliacao: 'Total',
      medidaCritica: 'Proteções da softstarter',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem tolerância',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ13-N',
      descricao: 'REGULAGEM RELÉ DE SOBRECARGA',
      etapa: 'MONTAGEM',
      avaliacao: 'Total',
      medidaCritica: 'Regulagem do relé',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem tolerância e de acordo com o desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ14-N',
      descricao: 'CONFERIR A TENSÃO DA FONTE ANTES DE ALIMENTAR O PAINEL PARA TESTES',
      etapa: 'MONTAGEM',
      avaliacao: 'Total',
      medidaCritica: 'Tensão da fonte',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem tolerância e de acordo com o desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ15-N',
      descricao: 'VERIFICAR SE TEM O ACRÍLICO NOS BARRAMENTOS DE FORÇA, IMPEDINDO ACESSO DO USUÁRIO',
      etapa: 'MONTAGEM',
      avaliacao: 'Total',
      medidaCritica: 'Acrílico nos barramentos',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem tolerância e de acordo com o desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ16-N',
      descricao: 'VERIFICAR SE O RECEPTOR ESTÁ INSTALADO NA LATERAL DA CAIXA',
      etapa: 'MONTAGEM',
      avaliacao: 'Total',
      medidaCritica: 'Receptor instalado',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem tolerância e de acordo com o desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
    {
      codigo: 'CQ17-N',
      descricao: 'VERIFICAR APERTO DOS PARAFUSOS DA FIXAÇÃO DO PAINEL ELÉTRICO',
      etapa: 'MONTAGEM',
      avaliacao: 'Total',
      medidaCritica: 'Aperto dos parafusos',
      metodoVerificacao: 'Visual',
      instrumento: 'N/A',
      criteriosAceitacao: 'Sem tolerância e de acordo com o desenho',
      opcoes: ['Conforme', 'Não conforme'],
      requerImagem: false,
    },
  ],
};

// ============================================================================
// Mapeamento de setores por código
// ============================================================================
export const CQ_SETORES: { [codigo: string]: CQSetor } = {
  'A': CQ_A_CORTE,
  'B': CQ_B_MONTAGEM,
  'C': CQ_C_CENTRAL_HIDRAULICA,
  'D': CQ_D_SOLDA_LADO_01,
  'E': CQ_E_SOLDA_LADO_02,
  'F': CQ_F_MONTAGEM_SOLDA_INFERIOR,
  'G': CQ_G_MONTAGEM_ELETRICA_HIDRAULICO,
  'H': CQ_H_MONTAGEM_CALHAS,
  'I': CQ_I_TRAVADOR_RODAS_LATERAL,
  'J': CQ_J_CAIXA_TRAVA_CHASSI,
  'K': CQ_K_TRAVA_CHASSI,
  'L': CQ_L_CAVALETE_TRAVA_CHASSI,
  'M': CQ_M_CENTRAL_HIDRAULICA_SUBCONJUNTOS,
  'N': CQ_N_PAINEL_ELETRICO,
};

// Função para obter perguntas por código do setor
export function getCQPerguntasBySetor(codigoSetor: string): CQPergunta[] {
  const setor = CQ_SETORES[codigoSetor];
  return setor ? setor.perguntas : [];
}

// Função para obter setor pelo nome da atividade
export function getCQSetorByAtividade(nomeAtividade: string): CQSetor | null {
  const codigoMatch = nomeAtividade.match(/^([A-Z])\s*-/);
  if (codigoMatch) {
    const codigo = codigoMatch[1];
    return CQ_SETORES[codigo] || null;
  }
  return null;
}
